<div id="pdp_shadow_item" class="  pdp_btn_block">
    <div class="font_outline_color">
        <div class="use_shadow">
            <label for="use_shadow"><span id="use_shadow"></span> <?php echo $this->__('Use Shadow'); ?></label>
        </div>
        <div class="h-shadow nodisplay">
            <label><?php echo $this->__('Offset Y') ?></label> 
            <div id="h-shadow"></div>
        </div>
        <div class="v-shadow nodisplay">
            <label><?php echo $this->__('Offset X') ?></label> 
            <div id="v-shadow"></div>
        </div>
        <div class="blur nodisplay">
            <label><?php echo $this->__('Blur') ?></label> 
            <div id="t-blur"></div>
        </div>
        <div class="color nodisplay">
            <div id="font_outline_color">
                <input type="text" id="font_outline_color_value" name="font_outline_color" value="#FFFFFF" />
            </div>
            <div id="font_outline_colorpicker"></div>
        </div>
    </div>
</div>