<?php 
$jsonFilename = $this->getData('pdpdesign');
$fileContent = Mage::helper('pdp')->getPDPJsonContent($jsonFilename);
$jsonContent = json_decode($fileContent);
$itemId = $this->getRequest()->getParam('item-id');
$images = Mage::helper('pdp')->getThumbnailImage($jsonFilename);
$productId = $this->getRequest()->getParam('product-id');
$sideHtml = Mage::helper("pdp")->getDesignSides($productId);
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "pdp/images/";
$orderId = $this->getRequest()->getParam('order-id');
?>
<html>
	<head>
		<title><?php echo 'Order '.$this->getRequest()->getParam("order-id"); echo $this->__(' - Final Design') ?></title>
		<link type="text/css" rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) ?>pdp/css/styles.css" />
		<link type="text/css" rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) ?>pdp/css/final_design.css" />
	</head>
	<body>
		<div class="reference_fonts" style="display: none">
			<?php echo $this->getLayout()->createBlock("core/template")->setTemplate("pdp/design/default_setting.phtml")->toHtml();?>
		</div>
		<div class="list-side" style="display: none;"><?php echo $sideHtml ?></div>
		<input type="hidden" value="<?php echo htmlentities($fileContent)?>" id="final_design_json"/>
		<input type="hidden" value="<?php echo Mage::helper('pdp')->getPdpBaseUrl(); ?>" id="base_url"/>
		<input type="hidden" value="<?php echo $productId ?>" id="product_id"/>
		<input type="hidden" value="<?php echo $orderId ?>" id="order_id"/>
		<input type="hidden" value="<?php echo $itemId ?>" id="item_id"/>
		<div style="text-align: center;background: #eee;padding-top: 20px;">
			<button class="export-btn download-svg" type="button"><?php echo $this->__('Download SVG') ?></button>
			<button class="export-btn download-png" type="button"><?php echo $this->__('Download PNG') ?></button>
			<button class="export-btn download-pdf" type="button"><?php echo $this->__('Download PDF') ?></button>
			<?php $printLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) . "pdp/print/index/jsonfile/" . $jsonFilename; ?>
			<!--<button onclick="window.location = '<?php echo $printLink ?>'" class="export-btn pdf-export" type="button"><?php echo $this->__("Download PDF Pages") ?></button> -->
			<?php $generalInfoLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) . "pdp/print/general/jsonfile/$jsonFilename/order-id/" . $this->getRequest()->getParam("order-id") ; ?>
			<button onclick="window.location = '<?php echo $generalInfoLink ?>'" class="export-btn txt-export" type="button"><?php echo $this->__('Download General Information') ?></button>
		</div>
		<div class="include-bg">
			<button class="export-btn download-png-bg" type="button"><?php echo $this->__('Download PNG Include Background') ?></button>
			<button onclick="window.location = '<?php echo $printLink ?>'" class="export-btn pdf-export" type="button"><?php echo $this->__("Download PDF Include Background") ?></button>
		</div>
		<div class="pdc-canvas" style="display: none;"></div>
		<div class="pdp_wrap">
			<dl class="item-options">
			<?php foreach ($images as $image) : ?>
				<dt style=" text-decoration: underline; border-top: #eee solid 1px; text-transform: uppercase; padding-top: 10px;">Side: <?php echo $this->__($image['name']) ?></dt>
				<dd><img src="<?php echo $image['image'] ?>" alt="Customize Image"/></dd>
			<?php endforeach; ?>
			</dl>
		</div>
		<div class="pdploading nodisplay"><span><?php echo $this->__('Please wait...');?></span></div>
		<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) ?>pdp/js/jquery.min.js"></script>
		<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) ?>pdp/js/fabric.js"></script>
		<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) ?>pdp/js/final_design.js"></script>
	</body>
</html>