<?php 
	$colors = Mage::getModel('pdp/color')->getColors();
?>
<div id="pdp_color_fill" class="">
    <div id="pdp_color_item">
        <div class="pdp_color_list">
            <ul>
            <li>
                <a style="background-color: transparent;" title="default color"><?php echo $this->__('Default')?></a>
            </li>
            <?php $i = 0; foreach($colors as $color)  :?>
                 <li><a style="background-color: #<?php echo $color->getColor_code(); ?>" title="<?php echo $color->getColor_name(); ?>"><?php echo $color->getColor_name(); ?></a></li>
                <?php $i++; endforeach;  ?>
            </ul>
            <p class="nodisplay nomore_color"><?php echo $this->__('No more color for this clipart.') ?></p>
        </div>
    </div>
</div> 