<?php
$params = Mage::app()->getRequest()->getParams(); 
$productId = $params['productid'];
$sides = Mage::getModel('pdp/pdpside')->getDesignSides($productId);
$sidePosition = $sideStatus = "";
$colors = Mage::getModel('pdp/color')->getColors();
?>

<link rel="stylesheet" type="text/css"
	href="<?php echo $this->getSkinUrl('boxes.css') ?>" />
<link type="text/css" rel="stylesheet"
	href="<?php echo $this->getJsUrl('pdp/css/printarea.css') ?>" />
<script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/form.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('pdp/js/jquery.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('pdp/js/backend/pdpdesign.js') ?>"></script>
<div class="pdp_message">
	<?php echo $this->getMessagesBlock()->toHtml(); ?>
</div>
<form id="add_design_color_form" method="POST"
	action="<?php echo Mage::helper("adminhtml")->getUrl("pdp/adminhtml_designarea/savedesigncolor/"); ?>"
	enctype="multipart/form-data">
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
	<div style="" id="designarea_tabs_form_section_content">
		<div class="entry-edit">
			<div class="entry-edit-head">
				<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('General Information') ?></h4>
				<div class="form-buttons">
					<button class="scalable delete"
						onclick="location.reload(); return false;" title="Reset">
						<span><span><span><?php echo $this->__('Reset') ?></span></span></span>
					</button>
					<button class="scalable save" type="submit" title="Save">
						<span><span><span><?php echo $this->__('Save') ?></span></span></span>
					</button>
				</div>
			</div>
			<div id="pdpdesignarea_pdp_form" class="fieldset ">
				<div class="hor-scroll">
					<div class="modal-footer">
						<div class="inlay-info">
							<input type="hidden" name="pdpcolor[product_id]" value="<?php echo $productId ?>" />
							<div class='design-area-input'>
								<label for="color_id"><?php echo $this->__('Select Color') ?> <span	class="required">*</span></label> 			
								<select id="color_id" name="pdpcolor[color_id]" class="required-entry select">
									<option value=''><?php echo $this->__('-- Please Select --')?></option>
									<?php foreach ($colors as $color) :?>
									<option style='background:<?php echo "#" . $color->getColorCode()   ?>' value="<?php echo $color->getId()?>">
										<?php echo $this->__($color->getColorName())?>
									</option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class='design-area-input'>
								<label for="pdpposition"><?php echo $this->__('Position') ?></label>
								<input type="text" class=" input-text validate-number"
									value="<?php echo $sidePosition ?>" name="pdpcolor[position]"
									id="pdpposition" />
							</div>
							<div class='design-area-input'>
								<label for="pdpstatus"><?php echo $this->__('Status') ?></label>
								<select class=" select" name="pdpcolor[status]" id="pdpstatus">
									<option <?php echo ($sideStatus == 1) ? "selected" : ""; ?>
										value="1"><?php echo $this->__('Enabled') ?></option>
									<option <?php echo ($sideStatus == 2) ? "selected" : ""; ?>
										value="2"><?php echo $this->__('Disabled') ?></option>
								</select>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="entry-edit-head">
				<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Image of current color for each side') ?></h4>
			</div>
			<div id="pdpdesignarea_pdp_form" class="fieldset ">
				<div class="hor-scroll">
					<table>
						<?php foreach ($sides as $side) :?>
						<tr>
							<td>
								<input type="hidden" name="design_sides[]" value="<?php echo $side->getId() ?>"/>
								<label for="color_name"><?php echo $this->__( $side->getLabel()) ?> <span class="required">*</span></label>
							</td>
							<td>
								<input type="file" onchange="PDPPopup.previewImage(this)" class="required-entry" name="color_image_<?php echo $side->getId() ?>" />
							</td>
							<td><img style='display: none' class='preview-image' id='preview-img-<?php echo $side->getId() ?>' src='' alt='Preview Image' width='100' height='100' /></td>
						</tr>
						<?php endforeach; ?>
					</table>
				</div>
			</div>
		</div>
	</div>
</form>
<script type="text/javascript">
	var addSideColorForm = new VarienForm('add_design_color_form', true);
</script>