<?php
/*------------------------------------------------------------------------
 # SM Deal - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
global $var_yttheme;
?>
		
<script type="text/javascript">
//<![CDATA[
data = new Date(2013,10,26,12,00,00);
var listdeal = [];
function CountDown(date,id){
	dateNow = new Date();
	amount = date.getTime() - dateNow.getTime();
	delete dateNow;
	if(amount < 0){
		document.getElementById(id).innerHTML="Now!";
	} else{
		days=0;hours=0;mins=0;secs=0;out="";
		amount = Math.floor(amount/1000);
		days=Math.floor(amount/86400);
		amount=amount%86400;
		hours=Math.floor(amount/3600);
		amount=amount%3600;
		mins=Math.floor(amount/60);
		amount=amount%60;
		secs=Math.floor(amount);
		if(days != 0){out += "<div class='time-item time-day'>" + "<div class='num-time'>" + days + "</div>" +" <div class='name-time'>"+((days==1)?"Day:":"Days:") + "</div>"+"</div> ";}
		if(hours != 0){out += "<div class='time-item time-hour'>" + "<div class='num-time'>" + hours + "</div>" +" <div class='name-time'>"+((hours==1)?"Hour:":"Hours:") + "</div>"+"</div> ";}
		out += "<div class='time-item time-min'>" + "<div class='num-time'>" + mins + "</div>" +" <div class='name-time'>"+((mins==1)?"Min:":"Mins:") + "</div>"+"</div> ";
		out += "<div class='time-item time-sec'>" + "<div class='num-time'>" + secs + "</div>" +" <div class='name-time'>"+((secs==1)?"Sec":"Secs") + "</div>"+"</div> ";
		out = out.substr(0,out.length-2);
		document.getElementById(id).innerHTML=out;
		setTimeout(function(){CountDown(date,id)}, 1000);
	}
}
//]]>
</script>
<?php
$dayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
$deals  = Mage::getResourceModel('deal/deal_product_collection')->joinFields()->joinFieldsdeal()
				->addFilter('status', '1', "=")
				->addFilter('end_date', $dayDate, ">");

if(Mage::getStoreConfig('deal/deal/orderby') == 1){
	$deals->OrderbyAdd('start_date','desc');
}else{
	$deals->OrderbyAdd('end_date','desc');
}
		
$productBlock=$this->getLayout()->createBlock("catalog/product_list");
$check_array =$deals->getData();

/*get config backend*/
$general_setting = Mage::getStoreConfig('deal/deal');
$product_setting = Mage::getStoreConfig('deal/product_display_setting');
$title_deal = Mage::getStoreConfig('deal/deal/title');
?>
<?php if( !empty($check_array) && $general_setting['isenabled'] == 1 ){
	$uniqued ='sm_deal_'.rand().time();
?>
<div class="title-deal">
	<h2><?php echo $title_deal;?></h2>
</div>
<div id="<?php echo $uniqued;?>" class="sm-deal-wrap">
	<div class="sm_imageslider slider-deal">
		<?php $j = 0; foreach($deals->getData() as $product_data){ 
					$_product = Mage::getModel('catalog/product')->load($product_data['entity_id']); 
					
					$now = date("Y-m-d H:m:s");
					$newsFrom= $_product->getNewsFromDate(); //substr($_product->getData('news_from_date'),0,10);
					$newsTo= $_product->getNewsToDate();   //substr($_product->getData('news_to_date'),0,10);
					
					$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
					//echo $specialprice . '-hau<br/>';
					$price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice();
					if ($specialprice == '' ) {
						$store_id = Mage::app()->getStore()->getStoreId();
						$discounted_price = Mage::getResourceModel('catalogrule/rule')->getRulePrice( 
										Mage::app()->getLocale()->storeTimeStamp($store_id), 
										Mage::app()->getStore($store_id)->getWebsiteId(), 
										Mage::getSingleton('customer/session')->getCustomerGroupId(), 
										$_product->getId());
						$specialprice = $discounted_price;
						
					}
					?>
					
					
					<div class="item item-deal item respl-item">
						<div class="item-inner">
							<div class="w-image-box">
								<span class="hover-background"></span>
								<div class="item-image">
									<a  href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">											
										<img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($product_setting['product_image_width'],$product_setting['product_image_height']); ?>"/>
									</a>
									
									<a title="<?php echo $this->__('View Details');?>" href="<?php echo $_product->getProductUrl() ?>" class="view-detail">
										<?php echo $this->__('View Details');?>
									</a>
								</div>
								
								<div class="label-wrapper">
								<?php if ($newsFrom !="" && $now>=$newsFrom && ($now<=$newsTo || $newsTo=="")){?>
									<div class="new-product">
										<?php echo $this->__('New'); ?>
									</div>
								<?php }?>
								</div>
								
								<?php if ( $specialprice ){ ?>
									<div class='sale-item'>
										<span class="txt-label"><?php echo $this->__('Save'); ?></span>
										<span class="n-sale">
											<?php
												$saleof= abs(($specialprice/($_product->getPrice()))*100-100);
												print_r(floor($saleof));
											?>%
										</span>
										
									</div>
								<?php }?>
								
								
							</div>
							
							<div class="item-info">
								<?php if( $product_setting['product_title_disp'] == 1 ){?>
								<div class="item-title">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
									<?php echo substr($this->htmlEscape($_product->getName()), 0, $product_setting['product_title_max_characters']);
									//echo $product_setting['product_title_max_characters'];
									?>
									</a>
								</div>
								<?php }?>
								
								<?php if( $product_setting['product_price_disp'] == 1 ){?>
								<div class="item-price">
									<?php if($_product->isSaleable()){
										echo $productBlock->getPriceHtml($_product, true); 
									} ?>
								</div>	
								<?php }?>
								
								<?php if( $product_setting['product_reviews_count'] == 1 ){?>
								<div class="item-review">
									<?php  echo $productBlock->getReviewsSummaryHtml($_product, false, true); ?>
								</div>
								<?php }?>
								
								
								
								<div class="item-time">	
									<div class="icon-timer"></div>
									<div class="item-timer" id="product_time_<?php echo $j;?>"></div>	
									<script type="text/javascript">
									//<![CDATA[
										listdeal.push('product_time_<?php echo $j."&&||&&".date("Y/m/d", strtotime($product_data['end_date']));?>') ;
									//]]>
									</script>											
								</div>
								<?php if( $product_setting['product_description_disp'] == 1 ){?>
									<div class="des-item">
									<?php 
										$max_leng = $product_setting['product_description_max_characters'];
										echo substr($_product->getShortDescription(), 0, $max_leng);
									?>
									</div>
								<?php }?>
								
								
							</div>
						</div>
					</div>
					<?php $j++; }?>	
	</div>	
</div>
<script>
		jQuery(document).ready(function($) {
			$('.slider-deal').owlCarousel({
				pagination: false,
				center: false,
				nav: true,
				//loop: false,
				margin: 30,
				navText: [ 'prev', 'next' ],
				slideBy: 1,
				autoplay: false,
				autoplayTimeout: 2500,
				autoplayHoverPause: true,
				autoplaySpeed: 800,
				startPosition: 1,
				responsive:{
					<?php if( $var_yttheme->getParam('device_responsive') == 1 ) {?>
						0:{
							items:1
						},
						480:{
							items:1
						},
						650:{
							items:2
						},
						768:{
							items:2
						},
						992:{
							items:3
						},
						1200:{
							items:4
						}
					<?php } else {?>
						0:{
							items:4
						},
						480:{
							items:4
						},
						650:{
							items:4
						},
						768:{
							items:4
						},
						1200:{
							items:4
						}
					<?php } ?>
				}
			});	  
		});	
</script>
<script type="text/javascript">
//<![CDATA[
window.onload=function(){
	if(listdeal.length > 0){
		for(i=0;i<listdeal.length;i++)
		{
			var arr = listdeal[i].split("&&||&&"); 
			var data = new Date(arr[1]);
			CountDown(data, arr[0]);
		}	
	}
};
//]]>
</script>	
<?php } ?>

