<?php 
	$imageId = Mage::app()->getRequest()->getParam('image_id');
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'pdp/images/artworks/';
	$filename = "";
	if ($imageId != "") {
		$model = Mage::getModel('pdp/images')->load($imageId);
		$filename = $model->getFilename();
	} 
?>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">	
			<div class="btn-group-top">
				<span class="title">Add Clipart Color</span>
			</div>
		</div>
		<div class="span6">	
			<div class="action-panel">
				<div class="btn-group">
					<button class="btn btn-success" type="button" onclick="history.back();" class="btn"><span>Back</span></button>
				</div>
				<div class="btn-group">
					<button type="button" class="btn btn-success" onclick="artworkForm.submit();" class="btn"><span>Save Color</span></button>
				</div>
			</div>
		</div>
	</div>
</div>
<form class="form-horizontal" id="artwork_color_form" name="artwork_color_form" method="POST" action="<?php echo Mage::helper("adminhtml")->getUrl("pdp/adminhtml_pdp/saveartworkcolor/"); ?>" enctype="multipart/form-data">
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
	<input type="hidden" id="media_url" value="<?php echo $mediaUrl ?>" />
	<input type='hidden' value='<?php echo $imageId; ?>' name='image_id'/>
	<div id='tshirt'>
		<div class="container-fluid">
			<div class="row-fluid">
				<div class="main-image span4">
					<img src="<?php echo $mediaUrl . $filename ?>" />
				</div>
				<div class="span8">
					<?php $counter = 1; ?>
					<input type='hidden' name='counter' id='counter' value='<?php echo $counter ?>' />
					<table class="table table-bordered" id='artwork_color_option'>
						<tr>
							<th>Color <span class="required">*</span></th>
							<th>Corresponding Clipart <span class="required">*</span></th>
							<th>Position</th>
							<th>Action</th>
						</tr>
						<tr>
							<td>
								<input type='text' class='span required-entry' id='colorpicker_1' name='color-image[1]' value='' />
							</td>
							<td><input type='file' class="required-entry" name='artworkimage_1' /></td>
							<td>
								<input type='text' class='span9 validate-digits' name='sort[1]' value=''/>
							</td>
							<td><button type='button' class="colorimage-option" id='removeimg_1'>Remove</button></td>
						</tr>
					</table>
					<button id='add_more_color_image' type='button'>Add More +</button>
				</div>
			</div>
		</div>
	</div>
</form>
<script type='text/javascript'>
	var artworkForm = new varienForm('artwork_color_form', '');
	var artworkColor = jQuery.noConflict();
	artworkColor(function($){
		//Active default option after page loaded
		Multicolor.activeColorPicker('#colorpicker_1');
	});
</script>