<?php
/*------------------------------------------------------------------------
 # SM Image Slider - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $this->_getProducts();
if(!empty($list)){
	$import_str = "";
	$jsHelper = Mage::helper('core/js');
		// jquery has not added yet
	if (!defined('MAGENTECH_JQUERY')  && (int)$this->_getConfig('include_jquery')){
		// if module allowed jquery.
		$import_str .= $jsHelper->includeSkinScript('sm/imageslider/js/jquery-1.8.2.min.js');
		$import_str .= $jsHelper->includeSkinScript('sm/imageslider/js/jquery-noconflict.js');
		define('MAGENTECH_JQUERY',1);
	}
	if (!defined('MAGENTECH_JQUERY_SLIDER')) {
		$import_str .= $jsHelper->includeSkinScript('sm/imageslider/js/owl.carousel.js');
		define('MAGENTECH_JQUERY_SLIDER',1);
	}
	echo $import_str;

	$tag_id = 'sm_imageslider_'.rand().time();
	$helper = Mage::helper('imageslider/data');

?>
	<div id="<?php echo $tag_id;?>" class="sm_imageslider_wrap">
		<?php if($this->_getConfig('pretext') != '') { ?>
			<div class="pre-text"><?php echo $this->_getConfig('pretext'); ?></div>
		<?php } ?>
		<?php if ( $this->_getConfig('slider_title_text') ){?>
			<div class="title-imageslider">
				<?php echo $this->_getConfig('slider_title_text');?>
			</div>
		<?php }?>
		
		<div class="sm_imageslider slider-deal">
		<?php foreach($list as $_product){?>
			<div class="item">				
				<a href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>" <?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?> >
					<img src="<?php echo $_product->_image ;?>" alt="<?php echo $_product->title; ?>" />
				</a>
			</div>
		<?php }?>
		</div>	
		
		<?php if( $this->_getConfig('posttext') != '' ) {  ?>
			<div class="post-text"><?php echo $this->_getConfig('posttext'); ?></div>
		<?php } ?>						 
    </div>	
	
<?php 	

?>	
	<script type="text/javascript">
	//<![CDATA[
		jQuery(document).ready(function($) {
			$('.slider-deal').owlCarousel({
				pagination: false,
				center: false,
				nav: true,
				loop: false,
				margin: 30,
				navText: [ 'prev', 'next' ],
				slideBy: 1,
				autoplay: false,
				autoplayTimeout: 2500,
				autoplayHoverPause: true,
				autoplaySpeed: 800,
				startPosition: 0, 
				responsive:{
					0:{
						items:1
					},
					480:{
						items:2
					},
					768:{
						items:3
					},
					1200:{
						items:3
					}
				}
			});	  
		});				
	//]]>
	</script>  	
	
<?php } else { echo $this->__('Has no item to show!');}?>
 