<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/styles.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/jquery.ui.core.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/jquery.mCustomScrollbar.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/colorbox.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/owl.carousel.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/pi-awesome.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/jquery.nouislider.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/farbtastic.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/stickytooltip.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/accordion.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/skin-1.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJSUrl('pdp/css/colour-icon.css') ?>"/>
<div class='design-btn' style="display: none">
<?php echo $this->getLayout()->createBlock('pdp/designbutton')->setTemplate('pdp/product/design_button.phtml')->toHtml() ?>
</div>
<div class='pdp_actions_backend'>
	<input type="hidden" id="is_backend" value="yes" />
</div>