<label><?php echo $this->__('Edit Item'); ?></label>
<div id="move_item">
	<span class="m_tl">TL</span>
	<span class="m_tc">TC</span>
	<span class="m_tr">TR</span>
	<span class="m_cl">CL</span>
	<span class="m_cc">CC</span>
	<span class="m_cr">CR</span>
	<span class="m_bl">BL</span>
	<span class="m_bc">BC</span>
	<span class="m_br">BR</span>
</div>
<div id="duplicate_item">
	<span><?php echo $this->__('Duplicate'); ?></span>
</div>
<div id="delete_item">
	<span><?php echo $this->__('Delete'); ?></span>
</div>
<div id="flip_items">
	<span class="flip_x"><?php echo $this->__('Flip X'); ?></span>
	<span class="flip_y"><?php echo $this->__('Flip Y'); ?></span>
</div>