<?php 
$facebookAppId = $facebookKey = "";
$facebookInfo = $this->getFacebookInfo();
if (is_array($facebookInfo)) {
	$facebookAppId = $facebookInfo['facebook_app_id'];
	$facebookKey = $facebookInfo['facebook_secret_key'];
}
?>
<input type="hidden" id="facebook_app_id" value="<?php echo $facebookAppId; ?>"/>
<input type="hidden" id="facebook_secret_key" value="<?php echo $facebookKey; ?>"/>
<script type="text/javascript">
var facebook_app_id = '<?php echo $facebookAppId; ?>';
(function() {
  var e = document.createElement('script'); e.async = true;
  e.src = document.location.protocol 
    + '//connect.facebook.net/en_US/all.js';
  document.getElementById('fb-root').appendChild(e);
}());
</script>