<div class="share-buttons">
	<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
		<a class="addthis_button_facebook"></a>
		<a class="addthis_button_twitter"></a>
		<!-- <a class="addthis_button_pinterest_share"></a> -->
		<a class="addthis_button_google_plusone_share"></a>
		<a class="addthis_button_email"></a>
	</div>
</div>
<input type="hidden" name="save_design_url" id="save_design_url" value="<?php echo $this->getBaseUrl() . "pdp/view/saveBeforeShare" ?>"/>
<input type="hidden" name="is_share_btn" id="is_share_btn" value=""/>
<input type="hidden" name="share_json" id="share_json" value=""/>
<div class="pinterest-share-thumbnail" style="position: absolute; top: -100000px; right: 100000px"></div>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5099b58f632bd3db"></script>